# Assignment 1 on the Basic Python

###  Q1.Create a list which should contain values of type float and integer at alternate position.

In [1]:
List=[1, 0.15, 4, 0.5, 3, 0.75, 7]

In [2]:
# a)Write single instruction to print all the Float values using negative indexing technique.

print([List[i] for i in range(-len(List), 0) if isinstance(List[i], float)])

[0.15, 0.5, 0.75]


In [3]:
# b)Write single instruction to print all the integer values using positive indexing technique.

print([List[i] for i in range(len(List)) if isinstance(List[i], int)])

[1, 4, 3, 7]


In [4]:
# c)Show the results of invalid indexing on same data.

try:
    print(List[10])
except IndexError as e:
    print(f"Error1: {e}")




Error1: list index out of range


In [5]:
# Q2.Write a program in python to check whether the number is Armstrong or not ?

def is_armstrong(num):
    num_to_str = str(num)
    num_digits = len(num_to_str)

    def power(base, exp):
        result = 1
        for _ in range(exp):
            result *= base
        return result

    sum_of_powers = 0
    for digit in num_to_str:
        sum_of_powers += power(int(digit), num_digits)

    return sum_of_powers == num

num = int(input("Enter a number: "))

if is_armstrong(num):
    print(f"{num} is an Armstrong number.")
else:
    print(f"{num} is not an Armstrong number.")


Enter a number:  153


153 is an Armstrong number.


In [6]:
# Q3 a) Create a MLlab class without any variables and methods

class MLlab:
    pass

In [7]:
# b) Create a child class named ‘MLlab’ that will inherit all of the variables and methods of the ‘Course’ class. Create the instance of child class and access the members from outside the class

class Course:
    def __init__(self, course_name, instructor):
        self.course_name = course_name
        self.instructor = instructor

    def display_course_info(self):
        print(f"Course Name: {self.course_name}")
        print(f"Instructor: {self.instructor}")

class MLlab(Course):
    def __init__(self, course_name, instructor, lab_number):
        super().__init__(course_name, instructor)
        self.lab_number = lab_number

    def display_lab_info(self):
        print(f"Lab Number: {self.lab_number}")

ml_lab_instance = MLlab("Machine Learning", "Tapas Kumar Mishra", 109)

ml_lab_instance.display_course_info()

ml_lab_instance.display_lab_info()


Course Name: Machine Learning
Instructor: Tapas Kumar Mishra
Lab Number: 109


In [8]:
# c) Implement Method overriding concept using Multiple inheritance and Multilevel Inheritance.


# Method Overriding with Multiple Inheritance
class Course:
    def show_info(self):
        print("This is a course.")

class Lab:
    def show_info(self):
        print("This is a lab.")

class MLlab(Course, Lab):
    def show_info(self):
        print("From Multiple Inheritence: This is a Machine Learning lab.")

ml_lab_instance = MLlab()

ml_lab_instance.show_info()


# Method Overriding with Multilevel Inheritance
class Course:
    def show_info(self):
        print("This is a course.")

class AdvancedCourse(Course):
    def show_info(self):
        print("This is an advanced course.")

class MLlab(AdvancedCourse):
    def show_info(self):
        print("From Multilevel Inheritence: This is a Machine Learning lab.")

ml_lab_instance = MLlab()

ml_lab_instance.show_info()


From Multiple Inheritence: This is a Machine Learning lab.
From Multilevel Inheritence: This is a Machine Learning lab.


In [9]:
# Q4) a)Create empty and full array in python.
import numpy as np

empty_array = np.empty((3, 3))
print("Empty Array:")
print(empty_array)

full_array = np.full((3, 3), 6)
print("Full Array:")
print(full_array)


Empty Array:
[[0.00e+000 0.00e+000 0.00e+000]
 [0.00e+000 0.00e+000 8.95e-321]
 [0.00e+000 0.00e+000 0.00e+000]]
Full Array:
[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [10]:
# b)Create any Two Dimentional array and then flatten that to one dimension in Python

two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Two-Dimensional Array:")
print(two_d_array)

flattened_array = two_d_array.flatten()
print("Flattened Array:")
print(flattened_array)


Two-Dimensional Array:
[[1 2 3]
 [4 5 6]]
Flattened Array:
[1 2 3 4 5 6]


In [12]:
# c) Create the array in python and save that to Text File through python program.
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])
print("Array to be saved:")
print(array)

np.savetxt('array.txt', array, fmt='%d')

print("Array saved to 'array.txt'")


Array to be saved:
[[1 2 3]
 [4 5 6]]
Array saved to 'array.txt'


In [13]:
# d)Create the array
# arr = [[1.3, 2.5, 3.6, np.nan],
# [2.6, 3.3, np.nan, 5.5],
# [2.1, 3.2, 5.4, 6.5]]
# And replace the NAN values with the average of columns.

import numpy as np

arr = np.array([[1.3, 2.5, 3.6, np.nan],
                [2.6, 3.3, np.nan, 5.5],
                [2.1, 3.2, 5.4, 6.5]])

print("Original Array:")
print(arr)

col_mean = np.nanmean(arr, axis=0)

indices = np.where(np.isnan(arr))

arr[indices] = np.take(col_mean, indices[1])

print("Array after replacing NaN values with column averages:")
print(arr)


Original Array:
[[1.3 2.5 3.6 nan]
 [2.6 3.3 nan 5.5]
 [2.1 3.2 5.4 6.5]]
Array after replacing NaN values with column averages:
[[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]
